# Generated by Django 3.2 on 2021-06-09 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210609_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='orderItem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.orderitem'),
        ),
    ]
